### ISSUE TITLE
ptmx doesn't play well with ioutil.ReadAll on Linux?

### ISSUE THREAD

**Issue by zmwangx** [creack/pty#100]
Consider this slight variation of the example in README:

```go
package main

import (
        "github.com/creack/pty"
        "fmt"
        "log"
        "io/ioutil"
        "os/exec"
)

func main() {
        c := exec.Command("grep", "--color=auto", "bar")
        f, err := pty.Start(c)
        if err != nil {
                panic(err)
        }

        go func() {
                f.Write([]byte("foo\n"))
                f.Write([]byte("bar\n"))
                f.Write([]byte("baz\n"))
                f.Write([]byte{4}) // EOT
        }()
        output, err := ioutil.ReadAll(f)
        if err != nil {
                log.Fatalf("error reading from pty: %#v; content read thus far: %v", err, string(output))
        }
        fmt.Print(string(output))
}
```

On Ubuntu 20.04 with go 1.13 or 1.14, I'm getting this error:

```
2020/07/02 13:08:25 error reading from pty: &os.PathError{Op:"read", Path:"/dev/ptmx", Err:0x5}; content read thus far: foo
bar
baz
bar
```

It seems `/dev/ptmx` is just... gone before `ioutil.ReadAll` could get an EOF? FWIW I have no problem reading with a `bufio.Scanner`, and the same code seems to work on macOS just fine.

I'm pretty new to golang and I suspect there's some intricacy of `ioutil.ReadAll` that I'm not seeing, so this might be more of a question than a bug report. Nevertheless, it would be nice if `ioutil.ReadAll` worked with ptmx. What do you think?

**Comment by creack** [comment]
This is indeed an expected error.

`ioutil.ReadAll` consider anything not `EOF` to be an error, which is quite useful pretty much everywhere.

Here, we have a slightly more complex situation where the ptmx is shared between processes. When the child dies and the parent tries to read, Linux will yield a pipe or i/o error.

When `ReadAll` fails, you can check the state of the process to know if you need to worry about the error.

To avoid the error altogether, you will need to implement a syscall `select(2)`  (not Go's builtin `select`) loop to watch for the state of the pity. You probably will want to add a signal handler to watch for `SIGCHLD` too.

Closing for now as it is outside the scope of this lib.

**Comment by zmwangx** [comment]
Thanks for the explanation!

**Comment by robinovitch61** [comment]
For others looking how to read the content into a string:
```
f.Write([]byte("bar\n"))
f.Write([]byte("baz\n"))
f.Write([]byte{4}) // EOT
buf := new(bytes.Buffer)
io.Copy(buf, f)
fmt.Println(buf.String())
```
