### ISSUE TITLE
Get Shell's entered command

### ISSUE THREAD

**Issue by MartyEz** [creack/pty#102]
Hello,

I am using the Shell example command.
I would like to know if i can get the full entered command in shell.
Besides, i want the keep the ability of getting each keystrokes ( raw mode)

i tried to get each key of input and proceed text manipulation ( backspace, del, arrows, ...). But it's not reliable 

Thank you

**Comment by creack** [comment]
To get the input, you can use a `io.MultiWriter` on the copy like this:

```go
        f, err := os.Create("/tmp/input")
        if err != nil {
                panic(err)
        }
        defer func() { _ = f.Close() }() // Best effort.

        // Copy stdin to the pty and the pty to stdout.
        go func() { _, _ = io.Copy(io.MultiWriter(ptmx, f), os.Stdin) }()
```

Note that you can also use `ioutil.TeeReader` if you prefer to tap the reading side, but the result would be the same.

Here is the result:

```
~/workspace/creack/pty/t(master ✗) go run main.go
bash-3.2$ ls -l
total 48
-rw-r--r--  1 gcharmes  500  1248 Aug  4 14:24 main.go
bash-3.2$ echo hello
hello
bash-3.2$ exit

~/workspace/creack/pty/t(master ✗) cat -e /tmp/input
ls -l^Mecho hello^M^D%
```

It starts bash, I type `ls -l` then `echo hello` and terminate with `ctrl-d`. The raw mode is still in place so each keystroke is captured one by one and the `/tmp/input` file contains everything I typed.

Closing for now as this is more about Go I/Os in general and not the pty lib. I'd recommend StackOverflow or the mailing list for further assistance.

**Comment by MartyEz** [comment]
The problem is when i use top and bottom arrows ( navigating terminal's history ), i can't get the shell's command. 
I was looking for something like fc command. I found a solution by parsing Stdout and searching for CRLF.
