### ISSUE TITLE
StartWithSize() fails when building with Golang 1.15

### ISSUE THREAD

**Issue by rkojedzinszky** [creack/pty#103]
I am using cri-o, and cri-o built with Golang 1.15 produces the following error when trying execing into a container, with tty:

```
$ cat ~/cri-ctty-error.txt 
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
error: Internal error occurred: error executing command in container: fork/exec /usr/sbin/runc: Setctty set but Ctty not valid in child
```

With Golang 1.14 this works fine. Perhaps this change is responsible for it: https://golang.org/doc/go1.15#syscall

**Comment by creack** [comment]
Can you confirm your lib version? We fixed this in v1.1.10 (https://github.com/creack/pty/releases/tag/v1.1.10)

**Comment by rkojedzinszky** [comment]
Sure, cri-o still uses 1.1.9. Sorry, I was not careful enough.

**Comment by creack** [comment]
No worries, better a version issue than an actual bug :)
