### ISSUE TITLE
Support command input and output record

### ISSUE THREAD

**Issue by Vegetarianz** [creack/pty#105]
Is there a way to record command input and output？

just like pty in python:
```
import os
import pty

record = open("record.log", 'ab')
def master_read(fd):
    data = os.read(fd, 1024)
    record.write(data)
    return data

pty.spawn("bash", master_read)
```
thanks!

**Comment by creack** [comment]
Yes. The library is very simple and doesn't do everything automatically as the python one does.
The [readme](https://github.com/creack/pty/blob/master/README.md#shell) provides an example of how to handle the raw mode and the resizing when spawning a shell.

This example can be extended to add recorded. To do so, replace the two Copy lines with:

```go
        record, err := os.Create("record.log")
        if err != nil {
                panic(err)
        }
        defer func() { _ = record.Close() }() // Best effort.

        go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
        _, _ = io.Copy(os.Stdout, io.TeeReader(ptmx, record))
```
