### ISSUE TITLE
pty.Start and pty.StartWithSize not working on ubuntu 20

### ISSUE THREAD

**Issue by saisrivathsa** [creack/pty#115]
When I try to run the command `pty.StartWithSize` with `/bin/zsh` as cmd arguement(tried with `/bin/bash` as well) I am getting the following error 
```
rpc error: code = Internal desc = :fork/exec /bin/zsh: no such file or directory 
```
Seeing the same error even if I use simple `pty.Start`
Can someone help me with this?

**Comment by creack** [comment]
This kind of question would be better suited for StackOverflow.

It is not related to the library. `rpc error` indicates some kind of remote call, which is not part of the lib. `fork/exec` is an error coming from the standard library.

The error means you do not have the `/bin/zsh` or `/bin/bash` binaries where you try to execute them (or that some of the dynamic libraries required by the binary are missing).

I would suggest using `/usr/bin/env zsh` or `/usr/bin/env bash` which is more flexible and will work in more environments.
If that doesn't do the trick, then I recommend reducing complexity, first remove the lib and use the standard library directly, if that doesn't help, reduce complexity further and remove the rpc library in the middle. Once you find the solution, you can bring back the libs.

Closing for now as it is outside the scope of this project.
