### ISSUE TITLE
TERM environment variable not set.

### ISSUE THREAD

**Issue by yaobo-lab** [creack/pty#119]
when i input "top"   pty output: TERM environment variable not set.
How to solve the thank you!

![image](https://user-images.githubusercontent.com/21329253/118912013-b8e25280-b959-11eb-866a-10692a7cf802.png)

**Comment by creack** [comment]
You can set the TERM environment via the cmd object, but it is usually a bad idea as it should be set by the parent process.

```go
        c := exec.Command("top")
        c.Env = []string{"TERM=xterm"}
```

Without more context, I can't provide more detail.

Closing for now as this is not related to the pty lib. I would suggest Stackoverflow for this kind of question.

Good luck.
