### ISSUE TITLE
[question]how to use `cd` command to change folder

### ISSUE THREAD

**Issue by kaisawind** [creack/pty#121]
go exec.Command can't use cd to change folder,`pty` pkg can do this?

**Comment by creack** [comment]
`cd` is a built-in command in the shell, it changes the current working directory. `exec.Command` can do that as well by setting the 'Dir' field.

the `pty` package is a wrapper for `exec.Command` that adds support for pseudo terminals, so outside the pseudo terminal management, it can do exactly what `exec.Command` can and can''t do.

Example:

```go
package main

import (
	"fmt"
	"os/exec"
)

func cd(dir string) {
	cmd := exec.Command("pwd")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s", out)
}

func main() {
	cd(".")
	cd("..")
	cd("/tmp")
	cd("/var/log")
}
```

Closing as this is not related to the lib.

For this kind of question, I would recommend StackOverflow, which has a very active community and is not limited to a single project/library.
