### ISSUE TITLE
stdin with command having a pager

### ISSUE THREAD

**Issue by bruth** [creack/pty#132]
Hi and thank you for this great library! I am attempting to run a shell command (`git diff`) and using pty to get the colorized and paging output. However I am noticing that although keystrokes do appear to making it to the pty file, it requires more keystrokes than normal. Here is the snippet of the program:

```go
func (c *Command) runPTY() error {
	cmd := exec.Command(c.Name, c.Args...)

	if c.Verbose {
		fmt.Fprintf(os.Stderr, "* Running command `%s`\n", cmd.String())
	}

	// This binds the tty to cmd's stdout, stderr, and stdin.
	f, err := pty.Start(cmd)
	if err != nil {
		return err
	}

	cstdout := c.Stdout
	if cstdout == nil {
		if c.Verbose {
			cstdout = os.Stdout
		} else {
			cstdout = ioutil.Discard
		}
	}

	cstdin := c.Stdin
	if cstdin == nil {
		cstdin = os.Stdin
	}

	go io.Copy(f, cstdin)
	go io.Copy(cstdout, f)

	return cmd.Wait()
}
```

Here is a screenshot of the command running. The first part of the diff up to `# Assign the program name` prints out fine, but then it doesn't fill the whole terminal. The pager kicks in and then when I hit spacebar or enter, it doesn't behave normally. It requires a few enter keystrokes to finally page to the next line, for example. The gaps between each line is me hitting enter until the next diff line shows up.

<img width="810" alt="Screen Shot 2021-11-03 at 7 43 34 AM" src="https://user-images.githubusercontent.com/515142/140054180-e4c68a79-847d-4924-af7e-7ca7f4bb5cb0.png">

**Comment by creack** [comment]
Not fully sure to understand the goal, but the issue would be the missing input setup. The easiest way is to set the raw mode, but you can also simply toggle ICANON if you only want to avoid printing.

Also, make sure to set your streams *before* starting the process. i.e. cstdout / cstdin should be set before calling `pty.Start`.

Using the input initialization from the README, tweaked to fit your snippet, I think it does what you expect:

```go
package main

import (
        "fmt"
        "io"
        "io/ioutil"
        "log"
        "os"
        "os/exec"
        "os/signal"
        "syscall"

        "github.com/creack/pty"
        "golang.org/x/term"
)

// Command wraps the underlying command?
//nolint:govet // TODO: Cleanup.
type Command struct {
        Verbose bool
        Name    string
        Args    []string

        Stdout io.Writer
        Stdin  io.ReadCloser
}

func (c *Command) runPTY() error {
        //nolint:gosec // Expected variable exec?
        cmd := exec.Command(c.Name, c.Args...)

        if c.Verbose {
                fmt.Fprintf(os.Stderr, "* Running command %q\n", cmd)
        }

        cstdout := ioutil.Discard
        if c.Stdout != nil {
                cstdout = c.Stdout
        } else if c.Verbose {
                cstdout = os.Stdout
        }

        cstdin := c.Stdin
        if cstdin == nil {
                cstdin = os.Stdin
        }

        ptmx, err := pty.Start(cmd)
        if err != nil {
                return err
        }

        // Init the input raw mode / resize loop.
        if closer := c.initInput(ptmx, cstdin); closer != nil {
                defer closer()
        }

        go func() { _, _ = io.Copy(ptmx, cstdin) }()  // Best effort.
        go func() { _, _ = io.Copy(cstdout, ptmx) }() // Best effort.

        return cmd.Wait()
}

func (c *Command) initInput(ptmx *os.File, cstdin io.ReadCloser) func() {
        // Check if the given input stream is a terminal.
        f, ok := cstdin.(*os.File)
        if !ok {
                return nil
        }
        fd := int(f.Fd())
        if !term.IsTerminal(fd) { // If we are not dealing with a terminal, stop here.
                return nil
        }

        ch := make(chan os.Signal, 1)
        signal.Notify(ch, syscall.SIGWINCH)
        go func() {
                for range ch {
                        if err := pty.InheritSize(f, ptmx); err != nil {
                                log.Printf("error resizing pty: %s", err)
                        }
                }
        }()
        ch <- syscall.SIGWINCH                        // Initial resize.
        defer func() { signal.Stop(ch); close(ch) }() // Cleanup signals when done.

        // Set stdin in raw mode.
        oldState, err := term.MakeRaw(fd)
        if err != nil {
                panic(err)
        }
        return func() { _ = term.Restore(fd, oldState) } // Best effort.
}

func test() error {
        c := Command{
                Name:    "git",
                Args:    []string{"diff"},
                Verbose: false,
                Stdout:  os.Stdout,
                Stdin:   os.Stdin,
        }
        return c.runPTY()
}

func main() {
        if err := test(); err != nil {
                log.Printf("Fail: %s", err)
                return
        }
}
```

**Comment by bruth** [comment]
Thank you, I really appreciate you taking the time to write this up.

> Not fully sure to understand the goal

There may be a simpler way of doing this, but I want to run a command that behaves just like it I ran it using a shell. That is, it shows colors in the terminal (if that is configured) and paging works, etc. Running `git diff` with the vanilla `exec.Command` results in non-interactive, plain text output. So I assumed that I needed to `pty` in order _appear_ to be a terminal to target command.

Using the code above, the colors are maintained and in a full-screen terminal it prints out (does not page), but when I resize the terminal and run it again, it behaves the same as in my first comment.

I also noticed if I tried to pipe the output of the command above to a pager (`more`), it looks like this:

<img width="910" alt="Screen Shot 2021-11-05 at 7 37 27 AM" src="https://user-images.githubusercontent.com/515142/140504851-e8a1b32e-7de7-4711-b6fa-126a0c5efb58.png">

I don't quote understand these layers of interactions, so please correct me if I am doing something dumb. Thanks!

**Comment by creack** [comment]
Colors are set by the process displaying text. It often has a check whether it is within a terminal or not to toggle it, but it is nothing more than an escape sequence. Using a PTY would allow you to "fake" having a terminal for processes in the background.

Seems like you want to use the real terminal and page around, the vanilla os/exec.Commnad works just fine without PTY, using os.Stdin / os.Stdout.

The "mess" you get when piping the output to `more` is expected, the point of the pty is to behave as a terminal (pty means pseudo terminal), i.e., the output is the final render that gets interpreted by your terminal emulator (iTerm / xterm / etc).

I couldn't reproduce the issue with paging or bad echo with the provided example.

Example without pty:

```go
package main

import (
        "fmt"
        "io"
        "io/ioutil"
        "log"
        "os"
        "os/exec"
)

// Command wraps the underlying command?
//nolint:govet // TODO: Cleanup.
type Command struct {
        Verbose bool
        Name    string
        Args    []string

        Stdout io.Writer
        Stdin  io.ReadCloser
}

func (c *Command) runPTY() error {
        //nolint:gosec // Expected variable exec?
        cmd := exec.Command(c.Name, c.Args...)

        if c.Verbose {
                fmt.Fprintf(os.Stderr, "* Running command %q\n", cmd)
        }

        cstdout := ioutil.Discard
        if c.Stdout != nil {
                cstdout = c.Stdout
        } else if c.Verbose {
                cstdout = os.Stdout
        }

        cstdin := c.Stdin
        if cstdin == nil {
                cstdin = os.Stdin
        }

        cmd.Stdin = cstdin
        cmd.Stdout = cstdout

        if err := cmd.Start(); err != nil {
                return err
        }

        return cmd.Wait()
}

func test() error {
        c := Command{
                Name:    "git",
                Args:    []string{"diff"},
                Verbose: false,
                Stdout:  os.Stdout,
                Stdin:   os.Stdin,
        }
        return c.runPTY()
}

func main() {
        if err := test(); err != nil {
                log.Printf("Fail: %s", err)
                return
        }
}
```

**Comment by bruth** [comment]
Thanks for the explanation. It appears there were a few programs I was calling that didn't show colors and thus I assumed I was doing it wrong and jumped to using pty. But it may the case the programs are not detecting properly. Some programs (like `git diff`) is rendering just fine. I will do some more testing.. but this is definitely not an issue with pty!
