### ISSUE TITLE
Reading from pty after process is finished.

### ISSUE THREAD

**Issue by zhiburt** [creack/pty#133]
Hi there,

So we have this code.

```go
package main

import (
        "io"
        "os"
        "os/exec"
        "time"

        "github.com/creack/pty"
)

func main() {
        c := exec.Command("echo", "Hello World")
        f, err := pty.Start(c)
        if err != nil {
                panic(err)
        }

        time.Sleep(time.Second * 5)

        io.Copy(os.Stdout, f)
}
```

On linux at the time the program is finished `Hello World` will be printed on the screen.
But it was noticed that on `freebsd` and `macos` nothing will be printed. (tested only on `freebsd` but I do believe on mac there will be the same result)

I am guessing it is related when the kernel cleans processes resources.
But its just assumptions, because as I remember linux && freebsd must behave in the same manner in this regard.

I am thinking if the behavior could adjusted to be the same.
Or at least for a sake of curiosity if anyone knows why it happens?

Thank you.

PS: I encounter this issue not actually with this library initially,
but I know not a lot of places where I could address such a question, so I checked your lib.

**Comment by creack** [comment]
This has to do with how the kernel implements the pts driver. OSX is based on BSD, so it may be using the same logic.

After some testing on osx and freebsd 13, it seems that the buffer gets cleared after 1 second.

Running the code on linux results in an error returned by io.Copy, which is indeed expected. It is one of the differences between. bsd/linux, BSD doesn't consider this an error, it simply result in 0 bytes read.

I didn't find a way to tweak this behavior though but there may be a ioctl I missed.

Reading on a closed resource is to be avoided. On Linux, it results in an error, on BSD, it results in unexpected behavior. I'd suggest to move things around slightly and add a sink that will always consume the data as it gets produced, so it can be used later on as a "regular" pipe.

**Comment by zhiburt** [comment]
> On Linux, it results in an error

But Hello World is printed on your machine correct?
Because on mine it is.

> I'd suggest to move things around slightly and add a sink that will always consume the data as it gets produced, so it can be used later on as a "regular" pipe.

What do you mean here?

**Comment by creack** [comment]
> Can I ask you how you verified that?
> *just wondering

Wrote a dummy test program and tested, again and again, and again. No "real" measurement, just got this from experiments.

> But Hello World is printed on your machine correct?
> Because on mine it is.

Correct, but the error is still there, which means something is wrong and the "good" comparison on Linux is actually failing too. It just happens that on Linux the failure occurs after displaying Hello World, but both cases (FreeBSD and Linux) are bad

> What do you mean here?

You can easily setup a goroutine before-hand to read from the pty continuously, then send that data via a channel somewhere else to be used, that way you control when to discard/clear the data.

**Comment by zhiburt** [comment]
Thanks for your response.

I think the issue can be closed,

> I'd suggest to move things around slightly and add a sink that will always consume the data as it gets produced, so it can be used later on as a "regular" pipe.
>
> > What do you mean here?
>
> You can easily setup a goroutine before-hand to read from the pty continuously, then send that data via a channel somewhere else to be used, that way you control when to discard/clear the data.

But correct me if I am wrong there will be no guarantee that we read 'everything' or 'til the EOF' at the end of the day.

**Comment by creack** [comment]
You will read 'everything' until the fd gets closed. Anything after the fd is closed is indeed not guaranteed.
