### ISSUE TITLE
shell example: "The goroutine will keep reading until the next keystroke before returning."

### ISSUE THREAD

**Issue by paullaffitte** [creack/pty#140]
Hello, I'm trying to use the shell example to spawn several shells sequentially (open shell1, close shell1, open shell2, close shell2...). The issue is that after closing the first shell, the first keystroke in the second shell is dropped. I think it's related to the note in the example code `// NOTE: The goroutine will keep reading until the next keystroke before returning.`.

How can I do to prevent this behavior?

Thanks!

**Comment by JohnGebbie** [comment]
Think I'm having the same issue. Did you find a solution?

**Comment by creack** [comment]
Sorry for the delay.

I haven't been able to reproduce. Could you provide a way to test this?

Note that to achieve this, you need a single read loop always reading on stdin and then managing the shells process. If you have both the exec and the read loop, indeed you may have some issues like this.

**Comment by creack** [comment]
Closing as it is likely related to the project using the lib rather than the lib.

Feel free to re-open if you still think it comes from the lib.
