### ISSUE TITLE
How to access the pseudo terminal's stderr?

### ISSUE THREAD

**Issue by tliron** [creack/pty#147]
Great library, thanks! I'm confused as to how to handle stderr. The returned `*os.File` is used for stdout and stdin, so where is stderr? Am I misunderstanding something?

**Comment by kr** [comment]
In unix, in general, you can use a terminal's file descriptor for any or all of stdin, stdout, and stderr. In this package, the `Start` functions assign the `*os.File` to all three, or if you use `Open` you can pick and choose.

**Comment by kr** [comment]
Oh I almost forgot, this package only does the assignment if those fields are nil. You give an `*exec.Cmd` to `Start`, and you can set `Stdin`, `Stdout`, and `Stderr` to whatever you want. This package will not change their values if you've set them to a non-nil value. If you leave them all nil, then you'll get the tty for all of them.

**Comment by tliron** [comment]
Thanks, I did try this and it does work ... but it makes the entire terminal behave incorrectly. I will try to debug this and see what is going wrong.

**Comment by tliron** [comment]
I'm a bit stuck with this. My application is a remote shell, and everything works fine until I set `command.Stderr` to anything at all (even `io.Discard`) before I call `pty.Start`. What happens then is that the remote command prompt is not sent to stdout. I'm struggling to understand how stderr and stdout could even be related here.

**Comment by tliron** [comment]
Some progress -- in the [documentation for exec](https://pkg.go.dev/os/exec#Cmd) I see this:

> 	// If either is an *os.File, the corresponding output from the process
> 	// is connected directly to that file.

That means that assigning the tty file to stderr is handled specially. So, I tried to create a named pipe file and attach it instead, but that still didn't work. So, I'm stuck. I want to redirect stderr elsewhere. Any ideas?

**Comment by kr** [comment]
> everything works fine until I set `command.Stderr` to anything at all (even `io.Discard`) before I call `pty.Start`. What happens then is that the remote command prompt is not sent to stdout.

It's a little hard to help you debug your program without knowing the lay of the land, but one question comes to mind:

Are you sure the child process is printing the prompt on its stdout? Sometimes shells do other things, especially if they detect that they're using a tty. It may simply be printing the prompt to stderr.

In my experience, usually the best thing to do is to give a shell its tty on all three standard fds, and then, if you need to do any redirection, do so using shell features inside the shell.

**Comment by tliron** [comment]
Thanks! In my case I am just running `/bin/bash` in pty, but I need to separate stderr from stdout. That's something I can't do if both stderr and stdout are on the same tty. And if stderr is not pointing to a file then it seems bash works incorrectly. I will continue experimenting and post results here in case someone else has the same problem.

**Comment by tliron** [comment]
As soon as I posted the above, my experiment succeeded. :) Here is what is needed to do to force bash to work with a non-file stderr: just use the `-i` flag:

```go
command := exec.Command("/bin/bash", "-i")

// Note: Our stderr is not a TTY file, which may cause some shell programs to disable their interactive mode.
// In such cases it may be possible to force interactive mode, for example: `bash -i`
command.Stderr = myStderrWriter;

if file, err := pty.Start(command); err == nil {
...
```

Thank you for your patience in trying to help me!

**Comment by tliron** [comment]
Actually, it occurred to me that you might want to enhance the example in your README to include "-i" and a redirection of stderr. As it stands, the example is incomplete in my view because stdout and stderr are combined.

**Comment by creack** [comment]
I think there is some misunderstanding of what a terminal/pty is. The terminal is the final rendering of the process, it is expected to combine stdout and stderr. If you have some advanced / special use case that would require special handling of stderr while still having stdout be a proper TTY, I am not sure this library would be able to accommodate it.

**Comment by tliron** [comment]
I understand that, but I'll also point out that this library wraps `exec.Command` and purports to support its features, such as separate streams for stdout and stderr. And indeed it does, though it requires some fiddling around, like I did by using "-i". In my experience my user case is a very common use case for remote shell applications.

I'm not suggesting you change any of the code, only that you add documentation or an example for this tricky little aspect. Anyway, it's your library and I'm just providing feedback. If people get stuck and search the web hopefully they will find this issue with my suggested workaround.
