### ISSUE TITLE
README examples fix

### ISSUE THREAD

**Issue by Anthony6075** [creack/pty#152]
In the README shell example, there is a line:
`ptmx, err := pty.Start(c)`
but maybe `ptm` is better than `ptmx` to be used as the variable name.
Because `ptmx` means "**pseudoterminal multiplexor**", which is used to create a pseudoterminal master and slave pair.(https://man7.org/linux/man-pages/man4/pts.4.html) Here, we just get a **pseudoterminal master** by calling `pty.Start(c)`. So, maybe `ptm` is better.

**Comment by creack** [comment]
Sorry for the delay. Looking at this now.

While indeed we have a single pseudo terminal master, it is the README and the idea is to describe what is going on, here the `ptmx` variable is a direct result of `os.Open("/dev/ptmx")`, using `ptm` may cause confusion.

I don't have any strong feelings about this, if you still think it would be best to rename it, let me know.

Closing for now, feel free to reopen.
