### ISSUE TITLE
GOOS=windows build on linux  undefined: pty.Start

### ISSUE THREAD

**Issue by mamh2021** [creack/pty#158]

**Comment by photostorm** [comment]
Windows is currently not supported in the master branch

**Comment by creack** [comment]
sorry for the delay. @mamh2021 couldyou provide more details and maybe an example to reproduce?

While Windows is indeed not supported yet (very soon to be), it should still be able to compile.

I did just find a similar issue, but with syscall.SIGWINCH, not with pty.Start.

**Comment by creack** [comment]
Closing as can't reproduce. Likely fixed in a recent version.
