### ISSUE TITLE
macOS kill tty after command, linux doesn't

### ISSUE THREAD

**Issue by caarlos0** [creack/pty#186]
While integrating this on [wish](https://github.com/charmbracelet/wish), I found a weird bug on macOS.

I'm not sure if I'm doing something wrong, or if this is to be expected and I'll have to work around it, but anyway, here it is:

- [charmbracelet/ssh has an option to allocate a pty per session](https://github.com/charmbracelet/ssh/blob/6d7cf11c8371c33c2f05ce293a29f56009ea24ef/options.go#L105-L112)
- ...[which will call pty.Open](https://github.com/charmbracelet/ssh/blob/6d7cf11c8371c33c2f05ce293a29f56009ea24ef/pty_unix.go#L78)
- on wish, we handle it to a bubbletea app, which will use the `tty` from `pty.Open` as IO
- eventually, the app will create a `exec.Cmd`, and run it 
- this causes bubbletea to restore the terminal to its previous state (i.e. restore the `tty` to its previous state)
- `Start` the `exec.Cmd` (setting the proper `SysProcAttr`
- `Wait` for the `exec.Cmd` to finish 
- finally, tries to restore the terminal to its "bubbletea state" (raw mode, maybe with altscreen, etc)

This last step fails on macOS. As far as I was able to figure out, once `exec.Cmd.Start` is called, the `tty` FD is no more.

Is this a bug somewhere, or should I open another pty to exec a command within the session? 

PS: added a repro of the issue without any ssh/wish/etc below.

<details>
<summary>reproducible using only creack/pty and x.term</summary>

This reproduces the issue without touching anything related to wish/ssh:

```go
package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"os/signal"
	"syscall"

	"github.com/creack/pty"
	"golang.org/x/term"
)

func main() {
	ptmx, tty, err := pty.Open()
	handle(err)
	defer func() { _ = ptmx.Close() }() // Best effort.
	fmt.Println("open")
	check(ptmx)
	check(tty)

	c := exec.Command("bash")
	c.Stdin, c.Stdout, c.Stderr = tty, tty, tty
	if c.SysProcAttr == nil {
		c.SysProcAttr = &syscall.SysProcAttr{}
	}
	c.SysProcAttr.Setctty = true
	c.SysProcAttr.Setsid = true

	handle(c.Start())

	// Handle pty size.
	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGWINCH)
	go func() {
		for range ch {
			if err := pty.InheritSize(os.Stdin, ptmx); err != nil {
				log.Printf("error resizing pty: %s", err)
			}
		}
	}()
	ch <- syscall.SIGWINCH                        // Initial resize.
	defer func() { signal.Stop(ch); close(ch) }() // Cleanup signals when done.

	// Set stdin in raw mode.
	oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
	handle(err)
	defer func() {
		_ = term.Restore(int(os.Stdin.Fd()), oldState)
		fmt.Println("done")
		check(ptmx)
		check(tty)
	}() // Best effort

	// Copy stdin to the pty and the pty to stdout.
	// NOTE: The goroutine will keep reading until the next keystroke before returning.
	go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
	go func() { _, _ = io.Copy(os.Stdout, ptmx) }()
	go func() { _, _ = io.Copy(os.Stderr, ptmx) }()

	handle(c.Wait())
}

func handle(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func check(f *os.File) {
	_, err := f.Stat()
	if err == nil {
		log.Println("fd", f.Fd(), f.Name(), "- ok")
	} else {
		log.Println("fd", f.Fd(), f.Name(), "- err:", err)
	}
}
```

</details>

**Comment by creack** [comment]
Thanks for the detailed report. I'll take a look when I get back home. What is the observed vs expected behavior of the code snippet?

**Comment by caarlos0** [comment]
> Thanks for the detailed report. I'll take a look when I get back home. What is the observed vs expected behavior of the code snippet?

oh, sorry, forgot the most important part 🤦

If you run that example on linux, it will end with the log saying the tty is ok.
If you run on mac, it'll say "bad file descriptor".

---

adding more, newer info, creating a new pty for the exec command seems to work... I'm still kinda curious why this happens though... I dig the source code quite a bit, but didn't find anything... I probably overlooked something 🤔 


Thanks for the great lib, btw 💜

**Comment by creack** [comment]
I reduced the snippet to this, which reproduces the described behavior:

<details>
<summary>reproducible using only creack/pty</summary>

```go
package main

import (
        "fmt"
        "log"
        "os"
        "os/exec"
        "syscall"

        "github.com/creack/pty"
)

func main() {
        ptmx, tty, err := pty.Open()
        if err != nil {
                panic(err)
        }
        defer func() { _ = ptmx.Close() }() // Best effort.

        fmt.Println("open")
        check(ptmx)
        check(tty)

        c := exec.Command("true")
        c.Stdin, c.Stdout, c.Stderr = tty, tty, tty
        if c.SysProcAttr == nil {
                c.SysProcAttr = &syscall.SysProcAttr{}
        }
        c.SysProcAttr.Setctty = true
        c.SysProcAttr.Setsid = true

        if err := c.Run(); err != nil {
                panic(err)
        }

        fmt.Println("done")
        check(ptmx)
        check(tty)
}

func check(f *os.File) {
        _, err := f.Stat()
        if err == nil {
                log.Println("fd", f.Fd(), f.Name(), "- ok")
        } else {
                log.Println("fd", f.Fd(), f.Name(), "- err:", err)
        }
}
```
</details>

That way, it clearly isolate the behavior, which has nothing to do with the terminal capabilities/modes.

It looks like a different implementation of the tty driver between unix and linux. In any case, the preferred way to use the lib is via `pty.Start`, which wraps everything. Note that this only returns the `ptmx` handler, which is expected as once the command is started, the parent process shouldn't have to touch the slave part, which is what the snippet is trying to do.

In that snippet, if you remove the SysProcAttr part, or just disabled the Setctty (which stands for Controlling TTY), the snippet works the same on both linux and OSX. When set, I feel like the OSX behavior makes more sense, it gives the control to the child, the parent trying to use it after that simply fails.

I don't think I understand your use-case though. Why do you need to interact with the slave part in the parent process?

Note that the Raw mode & various term capabilities should only be applied by the controlling process on its stdios, i.e. bubble tea should only set the raw mode on the "real" terminal, not on the pseudo ones.

**Comment by caarlos0** [comment]
Hey, thanks for checking this out!

I think I figured out what my problem was:

- the ssh session creates the pty
- I try to use that pty to run run some command
- giving the pty `setctty` is fine otherwise, but in this case, when the program exits it kills the pty

the solution is quite simply not giving `setctty` to the command on start, as the ssh session is controlling it.

that said, thanks for helping me figure this out 🙏
