### ISSUE TITLE
Is there a way to unblock `io.Copy(ptmx, os.Stdin)` after exiting the spawned shell

### ISSUE THREAD

**Issue by joshi4** [creack/pty#188]
Thanks for creating this package! 

I'm running into an issue where `pty` doesn't seem to play nice with https://github.com/charmbracelet/bubbletea. 

I observe that bubbletea programs hang until I press a key ( after exiting the spawned shell by typing exit or ctrl-d)  

I'm following the [example](https://github.com/creack/pty/issues/188)  in the README closely and I think this particular line below is causing the problem. 

~~~go
        // Copy stdin to the pty and the pty to stdout.
        // NOTE: The goroutine will keep reading until the next keystroke before returning.
        go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
~~~ 

The need for an extra keystroke to unblock that go-routine seems to be the main issue. 

Is there any way to exit the go routine that copies from stdin to ptmx when ptmx closes?

**Comment by joshi4** [comment]
I had cross posted this question in the bubbletea discord too and their reply lead me to 
[cancelreader](https://github.com/muesli/cancelreader), which is exactly what I was looking for. 

Since this issue is non deterministic, I will test it a bit more and follow up here if cancelReader does indeed fix everything.

**Comment by creack** [comment]
Can you specify your OS? I suspect it is OSX, right? We could set the read in non-block mode, but Golang has a bug on OSX resulting in this using 100% CPU. But it would also behave as you expect.

An alternative would be to use select (2) syscall (not go's select keyword) or to watch for SIGIO before read, that way you can be sure the Read call will not block, and it should work everywhere.

That is a bit outside the scope of the library though, as it deals more about I/Os than TTYs.

**Comment by creack** [comment]
For reference: https://github.com/golang/go/issues/22099

**Comment by joshi4** [comment]
verified that using the cancelreader works for now.

Thanks for the suggestion of using sigio too. If I run into corner cases with the cancel reader, I will give that a shot.
