### ISSUE TITLE
want to press 'tab' to complete command

### ISSUE THREAD

**Issue by Yigerrr** [creack/pty#190]
hello,
 i want to  press 'tab' to complete command or press 'up arrow' to get last command in my pty,but it can't. But if i input 'sudo su/n' with f.Write,then it can.i want to know why,and could i do this without 'sudo su'? thanks very much.

**Comment by Yigerrr** [comment]
i change “cmd := exec.Command("bin/sh")” to  “cmd := exec.Command("bin/bash")” to fix this question,but still confused.

**Comment by creack** [comment]
this would be a thing on the shell side, not on the library. If you compare `sh` with `bash` outside of the lib, you will see the same behavior.

Closing for now, but feel free to re-open if I missed something.
