### ISSUE TITLE
Separate stderr and stdout

### ISSUE THREAD

**Issue by gitargowithit** [creack/pty#194]
Hey all, I am using pty in my project to get some CLI tools to print with color. 

Is it possible to get back 3 files here, one as it is now where stdout & stderr are combined, and one where it is just stdout and the other stderr? This would really help with some string/file manipulation I want to do afterwards. Currently this is the only way I found to separate out stdout and stderr:

```
func RunCommand(command string) (stdout, stderr string, err error) {
	cmd := exec.Command("bash", "-c", command)

	var stderrBuf bytes.Buffer
	var stdoutBuf bytes.Buffer

	cmd.Stderr = &stderrBuf // this line redirects the stderr to the buffer

	ptmx, err := pty.StartWithSize(cmd, &pty.Winsize{Cols: 80, Rows: 24})
	if err != nil {
		return "", "", err
	}
	defer func() { _ = ptmx.Close() }()

	go func() {
		_, _ = stdcopy(&stdoutBuf, ptmx)
	}()

	if err := cmd.Wait(); err != nil {
		return stdoutBuf.String(), stderrBuf.String(), err
	}

	return stdoutBuf.String(), stderrBuf.String(), nil
}
```

However this means that I can't keep the original output ordering, if for example a CLI tool prints to stdout then stderr then back to stdout this ordering is lost.

Thanks for the project, would appreciate some insight here!

**Comment by creack** [comment]
Trying to split stdout and stderr would result in ioctl error as it doesn't make sense for the driver.
Think of the terminal as your computer screen. You have only one of those, regardless if it is stdout or stderr, it gets printed on your one screen. Same thing for the terminal.

I believe you may not need a TTY though, displaying colors is something up to the terminal emulator, the tty only passes through the ascii escape sequences which are in turn interpreted by your terminal emulator to display a color.

Some color libraries use the presence of a TTY to automatically toggle colors on/off, but that can be manually changed.

**Comment by gitargowithit** [comment]
Thanks @creack. How do you suggest passing in "mock tty" for the libraries to print with color? For some reason the tool I'm using won't allow me to force color output even with the `--colors` flag set.

**Comment by creack** [comment]
Well, you can use this library, but if you need a valid tty, you can't split stdout/stderr, otherwise, you will face 'invalid ioctl for device' errors.
I would recommend looking for a different tool that doesn't require a tty to display colors.
