### ISSUE TITLE
How to write CSI char into pty?

### ISSUE THREAD

**Issue by McDaddy** [creack/pty#198]
Can I manually input CSI characters into pty? such as cursor moving, deleting words...

I tried with `[]byte("\x1B[2K")` to remove line, but seems not work as expected.

**Comment by creack** [comment]
The CSI characters are interpreted by the terminal emulator, nor the PTY, so writing them to the PTY would work the same as writing them anywhere.

Can you expand a bit more what you mean by "not work as expected"? What is the behavior you are eperiencing?

**Comment by McDaddy** [comment]
> The CSI characters are interpreted by the terminal emulator, nor the PTY, so writing them to the PTY would work the same as writing them anywhere.
> 
> Can you expand a bit more what you mean by "not work as expected"? What is the behavior you are eperiencing?

Thanks @creack , for now, I use `\b` instead, then it works well now.
