### ISSUE TITLE
FYI, I reverted the changes to that file. This point is to make sure it compiles with go < 1.15 as 1.15 dropped support for darwin/32bits.

### ISSUE THREAD

**Issue by Sec32fun32** [creack/pty#200]
FYI, I reverted the changes to that file. This point is to make sure it compiles with go < 1.15 as 1.15 dropped support for darwin/32bits.

_Originally posted by @creack in https://github.com/creack/pty/pull/154#discussion_r1375265530_

**Comment by creack** [comment]
?
