### ISSUE TITLE
How do I pipe input into the Cmd

### ISSUE THREAD

**Issue by jackielii** [creack/pty#202]
Thanks for a great lib! 

I would like to pass some input to the program before attaching it to the pty. Tying to replicate `echo -e "hello\nworld" | fzf`, but replacing fzf with the program.

Following the example in README, I swap `bash` to `fzf`

```go
func test() error {
	// Create arbitrary command.
	c := exec.Command("fzf")

	// Start the command with a pty.
	ptmx, err := pty.Start(c)
	if err != nil {
		return err
	}
	// Make sure to close the pty at the end.
	defer func() { _ = ptmx.Close() }() // Best effort.

	// Handle pty size.
	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGWINCH)
	go func() {
		for range ch {
			if err := pty.InheritSize(os.Stdin, ptmx); err != nil {
				log.Printf("error resizing pty: %s", err)
			}
		}
	}()
	ch <- syscall.SIGWINCH                        // Initial resize.
	defer func() { signal.Stop(ch); close(ch) }() // Cleanup signals when done.

	// Set stdin in raw mode.
	oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
	if err != nil {
		panic(err)
	}
	defer func() { _ = term.Restore(int(os.Stdin.Fd()), oldState) }() // Best effort.

	// Copy stdin to the pty and the pty to stdout.
	// NOTE: The goroutine will keep reading until the next keystroke before returning.
	go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
	_, _ = io.Copy(os.Stdout, ptmx)

	return nil
}
```

And I run it with:

```sh
echo hello | program
```

I get `panic: inappropriate ioctl for device` when starting the pty

As soon as I set stdin or write to stdin, I get this error. E.g. 

```go
	c := exec.Command("fzf")
	c.Stdin = bytes.NewReader([]byte("foo\nbar\nbaz\n"))
```

So, how do I send data to stdin before attaching a pty and give `fzf` full control of the terminal?

**Comment by creack** [comment]
When you use a pipe, you don't have a tty. That is a unix thing, not related to the library. What are you trying to achieve? Wouldn't the stdlib `exec.Command` work for your use-case?

**Comment by jackielii** [comment]
If I just use exec.Command, `fzf` can't get access to the tty, so it just gets stuck. My current work around is to use external script to do this.

But to summerise what I want to achieve: I want to read from input, process it, then give the result to fzf which I want to launch via `exec.Command` and then give fzf the tty so that I can type to filter down the result.

**Comment by jackielii** [comment]
Currently my work around is like this:

I create a script called `fzf-words`

```sh
#!/usr/bin/env fish

set -l tmp_file (mktemp)
trap "rm -f $tmp_file" EXIT

while read line
    echo $line >>$tmp_file
end

set -l load_words "split-words $tmp_file"

fish -c "$load_words ' '| uniq"| fzf \
    --tac \
    --bind "ctrl-space:reload(fish -c \"$load_words ' '\")" \
    --bind "ctrl-/:reload(fish -c \"$load_words '-'\")" \
    --bind "tab:execute-silent(echo -n {} | pbcopy)+abort" \
    --bind "enter:execute-silent(kitty @ send-text --match state:overlay_parent {})+abort" \
    --header 'Tab: copy to clipboard; Enter: send to terminal; ctrl-space: split by space; ctrl-/: to split by /'
    
```

Within it `split-words` is a go program that split the input into words. I'd like to have the whole thing wrapped in a go program.

**Comment by creack** [comment]
Not sure to understand the issue. I am not familiar with fish, but trying `fzf` works well using the pipeline's tty (i.e. without trying to create a new one)

main.go:

```go
package main

import (
        "os"
        "os/exec"
)

func test() error {
        c := exec.Command("fzf")
        c.Stdin = os.Stdin
        c.Stdout = os.Stdout
        c.Stderr = os.Stderr
        return c.Run()
}

func main() {
        if err := test(); err != nil {
                panic(err)
        }
}
```

```bash
ls / | go run .
```

Example running `fzf` directly and with `exec.Command`:
![demo](https://github.com/user-attachments/assets/18ff8622-6e3d-467b-a49b-6344cea0c9e8)

**Comment by creack** [comment]
To process the input, you can use a pipe, example changing all case to uppercase while using `fzf`:

```go
package main

import (
	"bytes"
	"io"
	"os"
	"os/exec"
)

func test() error {
	c := exec.Command("fzf")

	r, w := io.Pipe()
	go func() {
		defer w.Close()
		for buf := make([]byte, 32*1024); ; {
			n, err := os.Stdin.Read(buf)
			if err != nil || n == 0 {
				break
			}
			if n2, err := w.Write(bytes.ToUpper(buf[:n])); err != nil || n2 != n {
				break
			}
		}
	}()

	c.Stdin = r
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr

	return c.Run()
}

func main() {
	if err := test(); err != nil {
		panic(err)
	}
}
```

![demo](https://github.com/user-attachments/assets/f1a74a3d-875a-447e-8712-dc09b43cb9ac)

**Comment by jackielii** [comment]
Hi @creack you're absolutely right! Somehow I walked into this trap thinking I needed a pseudo terminal but actually I didn't! I think my original program just forgot to connect the os.Stdout & os.Stderr to the cmd. I tried yours and it just works:

```go
package main

import (
	"os"
	"os/exec"
)

func test() error {
	c := exec.Command("fzf")

	w, _ := c.StdinPipe()
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr

	if err := c.Start(); err != nil {
		return err
	}

	w.Write([]byte("foo\nbar\nbaz\n"))
	w.Close()

	return c.Wait()
}

func main() {
	if err := test(); err != nil {
		panic(err)
	}
}

```
