### ISSUE TITLE
Web terminal websocket weird behavior when in docker container

### ISSUE THREAD

**Issue by FritzHeiden** [creack/pty#203]
Hi, thanks for this awesome library! I have a web app that uses xterm.js to open a terminal on the server. Data transfer between xterm.js and go pty is realized with a websocket connection. Works great until I put my application inside a docker container.

Here I write "test" then hit backspace four times:

[Screencast From 2024-11-07 12-59-43.webm](https://github.com/user-attachments/assets/b3c8fcf1-4755-4ddd-b388-edb4a1564b7e)

The code:

```golang
func (s *TerminalWebSocket) handle(context echo.Context) error {
	websocket.Handler(func(ws *websocket.Conn) {
		defer ws.Close()

		c := exec.Command(s.shellPath)
		c.Env = append(os.Environ(), "HOME="+home)
		c.Dir = home
		c.SysProcAttr = &syscall.SysProcAttr{}
		c.SysProcAttr.Credential = &syscall.Credential{Uid: uint32(uid), Gid: uint32(gid)}

		ptmx, err := pty.StartWithAttrs(c, &pty.Winsize{Rows: 43, Cols: 101}, c.SysProcAttr)
		if err != nil {
			fmt.Println(err)
			return
		}
		defer func() { _ = ptmx.Close() }()

		pty.Setsize(ptmx, &pty.Winsize{Rows: 43, Cols: 101})
		id := uuid.New().String()
		websocket.Message.Send(ws, id)
		s.terminals = append(s.terminals, TerminalHandle{Ptmx: ptmx, Id: id})
		go func() { _, _ = io.Copy(ptmx, ws) }()
		_, _ = io.Copy(ws, ptmx)
	}).ServeHTTP(context.Response(), context.Request())

	return nil
}
```

Again, works like a charm when I run in directly on my linux system. Only looks like this when inside a docker container.
I run Arch natively and Ubuntu in the docker container, don't know if that may cause the issue.

Any help is appreciated, thanks.

**Comment by creack** [comment]
Is the container ran with -t to allocate a tty?
-- 
Guillaume J. Charmes

**Comment by FritzHeiden** [comment]
Running the container with tty option solves the issue. Thanks!
