### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by stgraber** [creack/pty#27]
Can we get a ztypes_arm64.go?

Apparently those are auto-generated somehow so I won't be sending a pull-request for the change I've done locally here which is basically copying the amd64 one to arm64.

**Comment by paulzhol** [comment]
```mktypes.bash``` creates them from ```types.go``` based on ```GOARCH``` and ```GOOS``` enviornment variables. Assuming gccgo now has an arm64 ```GOARCH```, just run ```GOOS=linux GOARCH=arm64 mktypes.bash``` and submit the resulting file.

**Comment by creack** [comment]
Closing as the file is now in the repo.
