### ISSUE TITLE
pty issue

### ISSUE THREAD

**Issue by ShanthkumarS079** [creack/pty#40]
In the file ioctl.go i'm getting "Multiple markers at this line
    - undefined: syscall.SYS_IOCTL
    - not enough arguments in call to 
     syscall.Syscall"  for the line
"_, _, e := syscall.Syscall(syscall.SYS_IOCTL, fd, cmd, ptr)"
Could you please help me to resolve this issue.

**Comment by kevinpostal** [comment]
You trying to build this on Windows? Does not seem to work :/

**Comment by creack** [comment]
Going to close as too old. @ShanthkumarS079 if you are still having the issue, please feel free to re-open.
In any case, if you remember, it would be awesome if you could add more details on which os/arch/go version you were using so I could try to reproduce.
