### ISSUE TITLE
io.Copy blocked after closing

### ISSUE THREAD

**Issue by eudore** [creack/pty#88]
After ptmx is closed, io.Copy will not read and return an error.

example:

```golang
package main

import (
	"os/exec"
	"io"
	"fmt"
	"time"
	"github.com/creack/pty"
)

type w struct{}

func main() {
	cmd := exec.Command("bash")
	ptmx, err := pty.Start(cmd)
	if err != nil {
		panic(err)
	}
	go func() {
		time.Sleep(1* time.Second)
		fmt.Println("timeout")
		ptmx.Close()
	}()
	fmt.Println(io.Copy(&w{}, ptmx))
	fmt.Println("stop")
}

func (*w) Write(p []byte) (int,error) {
	return len(p), nil
}
```

example2:
```golang

func main() {
	cmd := exec.Command("bash")
	ptmx, err := pty.Start(cmd)
	if err != nil {
		panic(err)
	}
	go func() {
		time.Sleep(1 * time.Second)
		fmt.Println("timeout")
		ptmx.Close()
	}()
	body := make([]byte, 2048)
	for {
		n, err := ptmx.Read(body)
		if err != nil {
			fmt.Println(err)
			break
		}
		fmt.Println(body[0:n], err)
	}
	fmt.Println("stop")
}
```

**Comment by creack** [comment]
This seems like expected behavior.

Could you describe your use case and expected result more in detail?

`exec.Command.Start` forks the process, resulting the the duplication of the ptmx/tty pair file discriptor. When the ptmx gets closed in the parent, it doesn't close the child one.

**Comment by eudore** [comment]
Usually src or dest can exit after calling Close method io.Copy.

I hope that ptmx.Close will close the bidirectional io.Copy, so how should I close the pty accurately?
