### ISSUE TITLE
Running FFmpeg Command

### ISSUE THREAD

**Issue by D-sense** [creack/pty#91]
Hi.
Please I need help using this package to run FFmpeg. I need to run a command as below as be able to capture the result: 
```
ffmpeg -v quiet -i ../test_tracks/b.mp3 -f f32le -ac 1 -c:a pcm_f32le -ar 44100 pipe:1 | ./main - /dev/stdin
```
Thanks

**Comment by creack** [comment]
Are you sure you need this library? IIRC `ffmeg` doesn't require nor need a pty.

I'd suggest to look at https://godoc.org/os/exec instead

**Comment by D-sense** [comment]
Apology for late reply. Thanks for your input. I was able to run all ffmpeg commands needed via the standard cmd package from Go.
