### ISSUE TITLE
Getting ANSI output from arbitrary commands

### ISSUE THREAD

**Issue by fideloper** [creack/pty#92]
Hi!

I haven't wrapped my head around how assigning a TTY works, but I have a goal of running arbitrary commands in a way that makes the commands think a TTY is assigned and output ANSI color codes in their output (in a way that allows me to collect that output and store/display it).

It seems like this package would allow that, but all the examples I've found have had more complicated use cases. I wondering if I'm correct in that this package can help me there?

Thanks!

**Comment by fideloper** [comment]
Looks like this will do it:

```golang
package main

import (
	"bufio"
	"fmt"
	"github.com/creack/pty"
	"io"
	"log"
	"os"
	"os/exec"
)

func main() {
	// Run a command that would output ansi when isatty
	cmd := exec.Command("phpunit")
	cmd.Env = os.Environ()
	tty, err := pty.Start(cmd)
	if err != nil {
		panic(err)
	}

	defer tty.Close()

	go func() {
		buf := bufio.NewReader(tty)

		for {
			line, _, err := buf.ReadLine()

			if err == io.EOF {
				break
			}

			if err != nil {
				log.Fatalf("Error on buf.ReadLine: %v", err)
			}

			fmt.Println(string(line))
		}
	}()

	cmd.Wait()
}
```

**Comment by kr** [comment]
Yeah, your code looks pretty reasonable. Thanks for posting that follow-up! Closing this issue now since it seems like you've answered your own question, so there's nothing left to do here.
