### ISSUE TITLE
Saving IO of shell, making a ttyrec

### ISSUE THREAD

**Issue by MartyEz** [creack/pty#99]
Hello,
I would like to make a ttyrec. 
I would like to  save shell's inputs ( keystrokes per keystrokes ) and commands outputs.

I am using your  code to launch a shell in a pty : 

```
       c := exec.Command("bash")

        // Start the command with a pty.
        ptmx, err := pty.Start(c)
        if err != nil {
               return err
        }
        // Make sure to close the pty at the end.
        defer func() { _ = ptmx.Close() }() // Best effort.

        // Handle pty size.
        ch := make(chan os.Signal, 1)
        signal.Notify(ch, syscall.SIGWINCH)
        go func() {
                for range ch {
                        if err := pty.InheritSize(os.Stdin, ptmx); err != nil {
                                log.Printf("error resizing pty: %s", err)
                        }
                }
        }()
        ch <- syscall.SIGWINCH // Initial resize.

        // Set stdin in raw mode.
        oldState, err := terminal.MakeRaw(int(os.Stdin.Fd()))
        if err != nil {
                panic(err)
        }
        defer func() { _ = terminal.Restore(int(os.Stdin.Fd()), oldState) }() // Best effort.

        // Copy stdin to the pty and the pty to stdout.
        go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
        _, _ = io.Copy(os.Stdout, ptmx)
```

I can get some results with io.Copy and io.TeeReader but i have issues.

Do you have a simple method to do a ttyrec ?

Thanks a lot

**Comment by creack** [comment]
Could you provide more detail on what kind of issues you are having?
If you want an example, I'd suggest to look at asciinema, which used to be in Go before moving to python: https://github.com/asciinema/asciinema/tree/v1.1.0

In the code sample, `os.Stdin` is the input stream, so indeed `io.TeeReader` can be used to pipe it into a file for recording keystroke by keystroke, for the output, we read from `ptmx`, so you can also use `io.TeeReader` there.

Something like this should be working fine:

```go
recInput, _ := os.Create("/tmp/input")
recOutput, _ := os.Create("/tmp/output")

go func() { _, _ = io.Copy(ptmx, io.TeeReader(os.Stdin, recInput)) }()
_, _ = io.Copy(os.Stdout, io.TeeReader(ptmx, recOutput))
```

**Comment by MartyEz** [comment]
I was using Tee with a bytes.Buffer in another goroutine. I had sync problem and text formatting problem. But your method is nicer. Ty a lot

I will check asciinema, thanks you a lot
